const state={products:[],category:'All',query:''};
const $=s=>document.querySelector(s);
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function wa(code){const msg=`Hello Kaizen Concepts, I'm interested in product ${code}. Please share more details, availability and price.`;return 'https://wa.me/971505198130?text='+encodeURIComponent(msg)}
function prettyCategory(c){return c==='Office Furniture'?'Office Furniture':c}
function renderFilters(){const cats=['All',...new Set(state.products.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button class="filter ${state.category===c?'active':''}" data-cat="${esc(c)}">${esc(prettyCategory(c))}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderFilters();renderProducts()})}
function filtered(){const q=state.query.toLowerCase().trim();return state.products.filter(p=>(state.category==='All'||p.category===state.category)&&(!q||(p.code+' '+p.category+' '+p.finish+' '+p.description.join(' ')).toLowerCase().includes(q)))}
function renderProducts(){const items=filtered();$('#resultCount').textContent=`Showing ${items.length} of ${state.products.length} products`;$('#empty').hidden=items.length!==0;$('#productGrid').innerHTML=items.map(p=>`<article class="product"><div class="product-photo"><img src="${esc(p.image)}" alt="${esc(p.code)}" loading="lazy"></div><div class="product-body"><div class="product-category">${esc(p.category)}</div><h3>${esc(p.code)}</h3><div class="product-finish">${esc(p.finish||'Specifications available on request')}</div><div class="product-actions"><button class="small-btn" data-view="${esc(p.code)}">View details</button><a class="small-btn primary" href="${wa(p.code)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openModal(b.dataset.view))}
function openModal(code){const p=state.products.find(x=>x.code===code);if(!p)return;$('#modalImage').src=p.image;$('#modalImage').alt=p.code;$('#modalCategory').textContent=p.category;$('#modalTitle').textContent=p.code;$('#modalFinish').textContent=p.finish||'Finish / colour: available on request';$('#modalDescription').innerHTML=p.description.map(x=>`<li>${esc(x)}</li>`).join('');$('#modalWhatsApp').href=wa(p.code);$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){ $('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function init(){const r=await fetch('products.json');state.products=await r.json();renderFilters();renderProducts();const hero=state.products.filter(p=>p.image).slice(0,3);$('#heroShowcase').innerHTML=hero.map(p=>`<div class="hero-card"><img src="${esc(p.image)}" alt="${esc(p.code)}"></div>`).join('')}
$('#search').addEventListener('input',e=>{state.query=e.target.value;renderProducts()});document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('.menu').addEventListener('click',()=>{const n=$('.navlinks'),open=n.classList.toggle('open');$('.menu').setAttribute('aria-expanded',open)});document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>$('.navlinks').classList.remove('open')));init();
